---
db:
  mysql_root_username: root
  mysql_root_password: root
  mysql_port: "3306"
stacks:
        network: BootstrapNetStack
        web: WebInstanceStack
        app : AppInstanceStack
        db : DbInstanceStack
        eip : WebInstanceEIPStack
opencms_version: 10.5.1
opencms_checksum: 24b60b481770c8bd85e8defbc8f62ab06967a540b58431c35fa03869d170abb1
